version: '2.1'
orbs:
  node: circleci/node@4.2
jobs:
  test-working:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run: echo Working
workflows:
  build:
    jobs:
      - test-working
