version: '2.1'
orbs:
  node: circleci/node@4.2
jobs:
  test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run: console.log('Working')
workflows:
  deploy:
    jobs:
      - test
