version: '2.1'

orbs:
  node: circleci/node@4.2

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run: git pull
      - run: npm install
      - run: npm run build
      - store_artifacts:
          path: public/

  setup-and-deploy:
    executor: node/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - '40:b2:a1:00:6f:75:26:b3:bb:b7:4f:4e:53:37:e2:8f'
            - '97:73:ed:06:2f:29:97:e6:1d:12:3e:fc:ba:ed:82:23'
            - '85:f4:da:ac:6d:72:50:cc:85:e4:5f:c1:db:d7:25:0b'
      - run: git config --global user.email "billy@answeringlegal.com"
      - run: git config --global user.name "answeringLegal"
      - run: ssh -o StrictHostKeyChecking=no ringsavvy@ringsavvy.com -p2020 exit
      - run: git remote add cpanel ssh://ringsavvy@ringsavvy.com:2020/home/ringsavvy/repositories/ringsavvy-website
      - run: git remote -v
      - run: git add public/*
      - run: git commit --allow-empty -m 'CircleCI build and deploy'
      - run: git push origin main
      - run: git push cpanel main

workflows:
  build-and-deploy:
    jobs:
      - build
      - setup-and-deploy:
          requires:
            - build
          filters:
            branches:
              only: main
