version: '2.1'
orbs:
  node: circleci/node@4.2
jobs:
  build:
    machine:
      enabled: true
    steps:
      - checkout
      - run: echo build
  setup-and-deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run: git remote add cpanel ssh://ringsavvy@ringsavvy.com:2020/home/ringsavvy/repositories/ringsavvy-website
      - run: git remote -v

workflows:
  build-and-deploy:
    jobs:
      - build
      - setup-and-deploy:
          requires:
            - build
          filters:
            branches:
              only: main
