version: '2.1'

orbs:
  node: circleci/node@4.2

jobs:
  build:
    working_directory: ~/project
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ~/ringsavvy-website
          cache-path: node_modules
          override-ci-command: npm install
      - run: npm run build
      - store_artifacts:
          path: public/

  setup-and-deploy:
    executor: node/default
    steps:
      - checkout
      #
      - run: git config --global user.email "billy@answeringlegal.com"
      - run: git config --global user.name "answeringLegal"
      - run: git remote add cpanel ssh://ringsavvy@ringsavvy.com:2020/home/ringsavvy/repositories/ringsavvy-website
      - run: git remote -v
      - run: git add public/*
      - run: git commit -m 'CircleCI build deploy'
      - run: git push origin main

workflows:
  build-and-deploy:
    jobs:
      - build
      - setup-and-deploy:
          requires:
            - build
          filters:
            branches:
              only: main
